// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpeETYpTo0Eed3yNKlr64xPsYJz7bQ9DI',
    appId: '1:906915401388:web:d794ea123f38e9f9455909',
    messagingSenderId: '906915401388',
    projectId: 'wellnest1',
    authDomain: 'wellnest1.firebaseapp.com',
    storageBucket: 'wellnest1.firebasestorage.app',
    measurementId: 'G-WJK0134TCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxuUb5_Y2bJKePbG7unjZL4yhKF-FItk',
    appId: '1:906915401388:android:9911c4a62b737f33455909',
    messagingSenderId: '906915401388',
    projectId: 'wellnest1',
    storageBucket: 'wellnest1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgnqqg8x61eM2RtbLq6SmhBQI1sQ86O4U',
    appId: '1:906915401388:ios:7c22a792a06a171a455909',
    messagingSenderId: '906915401388',
    projectId: 'wellnest1',
    storageBucket: 'wellnest1.firebasestorage.app',
    iosBundleId: 'com.example.wellnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgnqqg8x61eM2RtbLq6SmhBQI1sQ86O4U',
    appId: '1:906915401388:ios:7c22a792a06a171a455909',
    messagingSenderId: '906915401388',
    projectId: 'wellnest1',
    storageBucket: 'wellnest1.firebasestorage.app',
    iosBundleId: 'com.example.wellnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpeETYpTo0Eed3yNKlr64xPsYJz7bQ9DI',
    appId: '1:906915401388:web:6985344a0c3d43a1455909',
    messagingSenderId: '906915401388',
    projectId: 'wellnest1',
    authDomain: 'wellnest1.firebaseapp.com',
    storageBucket: 'wellnest1.firebasestorage.app',
    measurementId: 'G-MGKK8KCSY1',
  );
}
